import type { PackagingProfile, ShippingService } from './shipping-estimator.js';

export const DEFAULT_SHIPPING_SERVICES: ShippingService[] = [
  {
    courier_code: 'ups',
    courier_name: 'UPS',
    service_code: 'ups_standard',
    service_name: 'UPS Standard',
    service_level: 'standard',
    shipment_mode: 'parcel',
    constraints: { max_weight_kg: 70, max_length_mm: 2740, max_girth_plus_length_mm: 4000, max_volume_litres: 1200 },
    metadata: { ready_for_api: true, category: 'parcel' },
  },
  {
    courier_code: 'ups',
    courier_name: 'UPS',
    service_code: 'ups_express',
    service_name: 'UPS Express Saver',
    service_level: 'express',
    shipment_mode: 'parcel',
    constraints: { max_weight_kg: 70, max_length_mm: 2740, max_girth_plus_length_mm: 4000, max_volume_litres: 1200 },
    metadata: { ready_for_api: true, category: 'parcel' },
  },
  {
    courier_code: 'dpd',
    courier_name: 'DPD',
    service_code: 'dpd_next_day',
    service_name: 'DPD Next Day',
    service_level: 'standard',
    shipment_mode: 'parcel',
    constraints: { max_weight_kg: 30, max_length_mm: 1750, max_girth_plus_length_mm: 3000, max_volume_litres: 500 },
    metadata: { ready_for_api: false, category: 'parcel' },
  },
  {
    courier_code: 'dhl',
    courier_name: 'DHL Parcel UK',
    service_code: 'dhl_parcel_uk',
    service_name: 'DHL Parcel UK',
    service_level: 'standard',
    shipment_mode: 'parcel',
    constraints: { max_weight_kg: 25, max_length_mm: 1200, max_girth_plus_length_mm: 3000, max_volume_litres: 350 },
    metadata: { ready_for_api: false, category: 'parcel' },
  },
  {
    courier_code: 'palletways',
    courier_name: 'Palletways',
    service_code: 'palletways_economy',
    service_name: 'Palletways Economy',
    service_level: 'economy',
    shipment_mode: 'pallet',
    constraints: {
      required_packaging_type: 'pallet',
      max_weight_kg: 700,
      max_length_mm: 1200,
      max_width_mm: 1000,
      max_height_mm: 2200,
      max_volume_litres: 2640,
    },
    metadata: { ready_for_api: false, category: 'pallet' },
  },
  {
    courier_code: 'palletforce',
    courier_name: 'Palletforce',
    service_code: 'palletforce_premium',
    service_name: 'Palletforce Premium',
    service_level: 'express',
    shipment_mode: 'pallet',
    constraints: {
      required_packaging_type: 'pallet',
      max_weight_kg: 700,
      max_length_mm: 1200,
      max_width_mm: 1000,
      max_height_mm: 2200,
      max_volume_litres: 2640,
    },
    metadata: { ready_for_api: false, category: 'pallet' },
  },
  {
    courier_code: 'manual',
    courier_name: 'Manual Selection',
    service_code: 'manual_standard',
    service_name: 'Manual Standard',
    service_level: 'standard',
    shipment_mode: 'parcel',
    constraints: {},
    metadata: { ready_for_api: false },
  },
  {
    courier_code: 'manual',
    courier_name: 'Manual Selection',
    service_code: 'manual_express',
    service_name: 'Manual Express',
    service_level: 'express',
    shipment_mode: 'parcel',
    constraints: {},
    metadata: { ready_for_api: false },
  },
  {
    courier_code: 'manual',
    courier_name: 'Manual Selection',
    service_code: 'manual_pallet',
    service_name: 'Manual Pallet',
    service_level: 'economy',
    shipment_mode: 'pallet',
    constraints: {},
    metadata: { ready_for_api: false },
  },
];

export const DEFAULT_PACKAGING_PROFILES: PackagingProfile[] = [
  {
    code: 'BOX-SMALL',
    name: 'Small Carton',
    package_type: 'parcel',
    inner_length_mm: 350,
    inner_width_mm: 250,
    inner_height_mm: 180,
    max_weight_grams: 10000,
    tare_weight_grams: 250,
    default_cost_gbp: 1.25,
  },
  {
    code: 'BOX-MEDIUM',
    name: 'Medium Carton',
    package_type: 'parcel',
    inner_length_mm: 500,
    inner_width_mm: 350,
    inner_height_mm: 250,
    max_weight_grams: 18000,
    tare_weight_grams: 450,
    default_cost_gbp: 2.1,
  },
  {
    code: 'PALLET-HALF',
    name: 'Half Pallet',
    package_type: 'pallet',
    inner_length_mm: 1200,
    inner_width_mm: 800,
    inner_height_mm: 1200,
    max_weight_grams: 350000,
    tare_weight_grams: 12000,
    default_cost_gbp: 18,
  },
  {
    code: 'PALLET-FULL',
    name: 'Full Pallet',
    package_type: 'pallet',
    inner_length_mm: 1200,
    inner_width_mm: 1000,
    inner_height_mm: 1800,
    max_weight_grams: 700000,
    tare_weight_grams: 18000,
    default_cost_gbp: 24,
  },
];

export function isMissingRelationError(err: unknown): boolean {
  const e = err as { code?: string; message?: string };
  return e?.code === '42P01' || (e?.message ?? '').toLowerCase().includes('relation') && (e?.message ?? '').toLowerCase().includes('does not exist');
}
