import type { PackagingProfile, ShippingService } from './shipping-estimator.js';

export const DEFAULT_SHIPPING_SERVICES: ShippingService[] = [
  {
    courier_code: 'ups',
    courier_name: 'UPS',
    service_code: 'ups_standard',
    service_name: 'UPS Standard',
    service_level: 'standard',
    shipment_mode: 'parcel',
    constraints: { required_packaging_type: 'parcel', max_weight_kg: 70, max_length_mm: 2740, max_girth_plus_length_mm: 4000, max_volume_litres: 1200 },
    metadata: { ready_for_api: true, category: 'parcel' },
  },
  {
    courier_code: 'ups',
    courier_name: 'UPS',
    service_code: 'ups_express',
    service_name: 'UPS Express Saver',
    service_level: 'express',
    shipment_mode: 'parcel',
    constraints: { required_packaging_type: 'parcel', max_weight_kg: 70, max_length_mm: 2740, max_girth_plus_length_mm: 4000, max_volume_litres: 1200 },
    metadata: { ready_for_api: true, category: 'parcel' },
  },
  {
    courier_code: 'ups',
    courier_name: 'UPS',
    service_code: 'ups_express_worldwide',
    service_name: 'UPS Worldwide Express',
    service_level: 'express',
    shipment_mode: 'parcel',
    constraints: { required_packaging_type: 'parcel', max_weight_kg: 70, max_length_mm: 2740, max_girth_plus_length_mm: 4000, max_volume_litres: 1200 },
    metadata: { ready_for_api: false, category: 'parcel' },
  },
  {
    courier_code: 'ups',
    courier_name: 'UPS',
    service_code: 'ups_express_plus',
    service_name: 'UPS Worldwide Express Plus',
    service_level: 'express',
    shipment_mode: 'parcel',
    constraints: { required_packaging_type: 'parcel', max_weight_kg: 70, max_length_mm: 2740, max_girth_plus_length_mm: 4000, max_volume_litres: 1200 },
    metadata: { ready_for_api: false, category: 'parcel' },
  },
  {
    courier_code: 'ups',
    courier_name: 'UPS',
    service_code: 'ups_expedited',
    service_name: 'UPS Worldwide Expedited',
    service_level: 'standard',
    shipment_mode: 'parcel',
    constraints: { required_packaging_type: 'parcel', max_weight_kg: 70, max_length_mm: 2740, max_girth_plus_length_mm: 4000, max_volume_litres: 1200 },
    metadata: { ready_for_api: false, category: 'parcel' },
  },
  {
    courier_code: 'ups',
    courier_name: 'UPS',
    service_code: 'ups_express_freight',
    service_name: 'UPS Worldwide Express Freight',
    service_level: 'express',
    shipment_mode: 'freight',
    constraints: { required_packaging_type: 'freight', max_weight_kg: 500, max_length_mm: 3000, max_volume_litres: 5000 },
    metadata: { ready_for_api: false, category: 'freight' },
  },
  {
    // DHL Parcel UK — Zone A (England & Wales domestic)
    // Ovara Indicative Rates — editable via settings UI.
    courier_code: 'dhl',
    courier_name: 'DHL',
    service_code: 'dhl_parcel_zone_a',
    service_name: 'DHL Parcel UK — Zone A (England & Wales)',
    service_level: 'standard',
    shipment_mode: 'parcel',
    constraints: { required_packaging_type: 'parcel', max_weight_kg: 25 },
    metadata: {
      ready_for_api: false,
      category: 'parcel',
      integration_type: 'weight_size_tiers',
      zone: 'A',
      postcode_ranges: ['All UK Postcodes in England & Wales (except PO30–PO41, TR21–TR25)'],
      surcharge_areas: [{ name: 'Isle of Wight', codes: 'PO30–PO41', surcharge_gbp: 5.99 }, { name: 'Isle of Scilly', codes: 'TR21–TR25', surcharge_gbp: 5.99 }],
      tiers: [
        { name: 'Up to 25kg (NWD)', max_weight_kg: 25, service_level: 'next_working_day', cost_gbp: 5.75, per_kg_over: 0.29 },
        { name: 'Up to 25kg (2nd+)', max_weight_kg: 25, service_level: 'standard', cost_gbp: 4.50, per_kg_over: 0.29 },
      ],
      timed_services: [
        { name: 'Next Working Day By Noon', surcharge_gbp: 5.71 },
        { name: 'Next Working Day by 10:30am', surcharge_gbp: 6.89 },
        { name: 'Saturday', surcharge_gbp: 17.57 },
        { name: 'Saturday by 10:30am', surcharge_gbp: 12.19 },
      ],
      bagit_packs: [
        { size: 'Small', weight_range_kg: '1–2', cost_gbp: 4.90 },
        { size: 'Medium', weight_range_kg: '2+', cost_gbp: 4.90 },
        { size: 'Large', weight_range_kg: '5+', cost_gbp: 4.90 },
      ],
      surcharges: {
        heavy_weight_kg: [
          { min_kg: 5.01, max_kg: 10, surcharge_gbp: 1.50 },
          { min_kg: 10.01, max_kg: 20, surcharge_gbp: 15.00 },
          { min_kg: 20.01, max_kg: 30, surcharge_gbp: 25.00 },
          { min_kg: 30.01, max_kg: 32, surcharge_gbp: 30.00 },
          { min_kg: 34.01, max_kg: 36, surcharge_gbp: 40.00 },
          { min_kg: 36.01, max_kg: 500, surcharge_gbp: 50.00 },
        ],
        long_length_cm: [
          { min_cm: 100, max_cm: 119.99, surcharge_gbp: 1.00 },
          { min_cm: 120, max_cm: 139.99, surcharge_gbp: 5.00 },
          { min_cm: 140, max_cm: 159.99, surcharge_gbp: 6.00 },
          { min_cm: 160, max_cm: 179.99, surcharge_gbp: 9.00 },
          { min_cm: 180, max_cm: 199.99, surcharge_gbp: 14.00 },
          { min_cm: 200, max_cm: 219.99, surcharge_gbp: 21.00 },
          { min_cm: 220, max_cm: 239.99, surcharge_gbp: 26.00 },
          { min_cm: 240, max_cm: 259.99, surcharge_gbp: 31.00 },
          { min_cm: 260, max_cm: 279.99, surcharge_gbp: 39.00 },
          { min_cm: 280, max_cm: 299.99, surcharge_gbp: 51.00 },
          { min_cm: 300, max_cm: 319.99, surcharge_gbp: 56.00 },
          { min_cm: 320, max_cm: 339.99, surcharge_gbp: 65.00 },
          { min_cm: 340, max_cm: 10000, surcharge_gbp: 76.00 },
        ],
        other_services: [
          { name: 'Return to Sender', surcharge_gbp: 4.50, unit: 'per shipment' },
          { name: 'Compensation Charge', surcharge_gbp: 7.50, unit: 'per shipment' },
          { name: 'Carriage Charge', surcharge_gbp: 0.125, unit: 'per item' },
          { name: 'Booked in Delivery', surcharge_gbp: 15.99, unit: 'per item' },
          { name: 'Peak Surcharge', surcharge_gbp: 0.50, unit: 'per item' },
        ],
      },
      volumetric_divisor_cc_per_kg: 4000,
    },
  },
  {
    // DHL Parcel UK — Zone B (Scotland Lowlands & Central)
    courier_code: 'dhl',
    courier_name: 'DHL',
    service_code: 'dhl_parcel_zone_b',
    service_name: 'DHL Parcel UK — Zone B (Scotland Central)',
    service_level: 'standard',
    shipment_mode: 'parcel',
    constraints: { required_packaging_type: 'parcel', max_weight_kg: 25 },
    metadata: {
      ready_for_api: false,
      category: 'parcel',
      integration_type: 'weight_size_tiers',
      zone: 'B',
      postcode_ranges: ['DD', 'DG', 'EH', 'FK1–FK16', 'G', 'KA (exc KA27 & KA28)', 'KY', 'ML', 'TD'],
      tiers: [
        { name: 'Up to 25kg (NWD)', max_weight_kg: 25, service_level: 'next_working_day', cost_gbp: 5.75, per_kg_over: 0.29 },
        { name: 'Up to 25kg (2nd+)', max_weight_kg: 25, service_level: 'standard', cost_gbp: 4.50, per_kg_over: 0.29 },
      ],
      timed_services: [
        { name: 'Next Working Day By Noon', surcharge_gbp: 5.71 },
        { name: 'Next Working Day by 10:30am', surcharge_gbp: 6.89 },
        { name: 'Saturday', surcharge_gbp: 17.57 },
        { name: 'Saturday by 10:30am', surcharge_gbp: 12.19 },
      ],
      bagit_packs: [
        { size: 'Small', weight_range_kg: '1–2', cost_gbp: 4.90 },
        { size: 'Medium', weight_range_kg: '2+', cost_gbp: 4.90 },
        { size: 'Large', weight_range_kg: '5+', cost_gbp: 4.90 },
      ],
      surcharges: {
        heavy_weight_kg: [
          { min_kg: 5.01, max_kg: 10, surcharge_gbp: 1.50 },
          { min_kg: 10.01, max_kg: 20, surcharge_gbp: 15.00 },
          { min_kg: 20.01, max_kg: 30, surcharge_gbp: 25.00 },
          { min_kg: 30.01, max_kg: 32, surcharge_gbp: 30.00 },
          { min_kg: 34.01, max_kg: 36, surcharge_gbp: 40.00 },
          { min_kg: 36.01, max_kg: 500, surcharge_gbp: 50.00 },
        ],
        long_length_cm: [
          { min_cm: 100, max_cm: 119.99, surcharge_gbp: 1.00 },
          { min_cm: 120, max_cm: 139.99, surcharge_gbp: 5.00 },
          { min_cm: 140, max_cm: 159.99, surcharge_gbp: 6.00 },
          { min_cm: 160, max_cm: 179.99, surcharge_gbp: 9.00 },
          { min_cm: 180, max_cm: 199.99, surcharge_gbp: 14.00 },
          { min_cm: 200, max_cm: 219.99, surcharge_gbp: 21.00 },
          { min_cm: 220, max_cm: 239.99, surcharge_gbp: 26.00 },
          { min_cm: 240, max_cm: 259.99, surcharge_gbp: 31.00 },
          { min_cm: 260, max_cm: 279.99, surcharge_gbp: 39.00 },
          { min_cm: 280, max_cm: 299.99, surcharge_gbp: 51.00 },
          { min_cm: 300, max_cm: 319.99, surcharge_gbp: 56.00 },
          { min_cm: 320, max_cm: 339.99, surcharge_gbp: 65.00 },
          { min_cm: 340, max_cm: 10000, surcharge_gbp: 76.00 },
        ],
        other_services: [
          { name: 'Return to Sender', surcharge_gbp: 4.50, unit: 'per shipment' },
          { name: 'Compensation Charge', surcharge_gbp: 7.50, unit: 'per shipment' },
          { name: 'Carriage Charge', surcharge_gbp: 0.125, unit: 'per item' },
          { name: 'Booked in Delivery', surcharge_gbp: 15.99, unit: 'per item' },
          { name: 'Peak Surcharge', surcharge_gbp: 0.50, unit: 'per item' },
        ],
      },
      volumetric_divisor_cc_per_kg: 4000,
    },
  },
  {
    // DHL Parcel UK — Zone C (Northern Ireland)
    courier_code: 'dhl',
    courier_name: 'DHL',
    service_code: 'dhl_parcel_zone_c',
    service_name: 'DHL Parcel UK — Zone C (Northern Ireland)',
    service_level: 'standard',
    shipment_mode: 'parcel',
    constraints: { required_packaging_type: 'parcel', max_weight_kg: 25 },
    metadata: {
      ready_for_api: false,
      category: 'parcel',
      integration_type: 'weight_size_tiers',
      zone: 'C',
      postcode_ranges: ['BT'],
      tiers: [
        { name: 'Up to 25kg (NWD)', max_weight_kg: 25, service_level: 'next_working_day', cost_gbp: 9.00, per_kg_over: 0.55 },
        { name: 'Up to 25kg (2nd+)', max_weight_kg: 25, service_level: 'standard', cost_gbp: 7.00, per_kg_over: 0.55 },
      ],
      timed_services: [
        { name: 'Next Working Day By Noon', surcharge_gbp: 5.71 },
        { name: 'Next Working Day by 10:30am', surcharge_gbp: 6.89 },
        { name: 'Saturday', surcharge_gbp: 17.57 },
        { name: 'Saturday by 10:30am', surcharge_gbp: 12.19 },
      ],
      bagit_packs: [
        { size: 'Small', weight_range_kg: '1–2', cost_gbp: 4.90 },
        { size: 'Medium', weight_range_kg: '2+', cost_gbp: 4.90 },
        { size: 'Large', weight_range_kg: '5+', cost_gbp: 4.90 },
      ],
      surcharges: {
        heavy_weight_kg: [
          { min_kg: 5.01, max_kg: 10, surcharge_gbp: 1.50 },
          { min_kg: 10.01, max_kg: 20, surcharge_gbp: 15.00 },
          { min_kg: 20.01, max_kg: 30, surcharge_gbp: 25.00 },
          { min_kg: 30.01, max_kg: 32, surcharge_gbp: 30.00 },
          { min_kg: 34.01, max_kg: 36, surcharge_gbp: 40.00 },
          { min_kg: 36.01, max_kg: 500, surcharge_gbp: 50.00 },
        ],
        long_length_cm: [
          { min_cm: 100, max_cm: 119.99, surcharge_gbp: 1.00 },
          { min_cm: 120, max_cm: 139.99, surcharge_gbp: 5.00 },
          { min_cm: 140, max_cm: 159.99, surcharge_gbp: 6.00 },
          { min_cm: 160, max_cm: 179.99, surcharge_gbp: 9.00 },
          { min_cm: 180, max_cm: 199.99, surcharge_gbp: 14.00 },
          { min_cm: 200, max_cm: 219.99, surcharge_gbp: 21.00 },
          { min_cm: 220, max_cm: 239.99, surcharge_gbp: 26.00 },
          { min_cm: 240, max_cm: 259.99, surcharge_gbp: 31.00 },
          { min_cm: 260, max_cm: 279.99, surcharge_gbp: 39.00 },
          { min_cm: 280, max_cm: 299.99, surcharge_gbp: 51.00 },
          { min_cm: 300, max_cm: 319.99, surcharge_gbp: 56.00 },
          { min_cm: 320, max_cm: 339.99, surcharge_gbp: 65.00 },
          { min_cm: 340, max_cm: 10000, surcharge_gbp: 76.00 },
        ],
        other_services: [
          { name: 'Return to Sender', surcharge_gbp: 4.50, unit: 'per shipment' },
          { name: 'Compensation Charge', surcharge_gbp: 7.50, unit: 'per shipment' },
          { name: 'Carriage Charge', surcharge_gbp: 0.125, unit: 'per item' },
          { name: 'Booked in Delivery', surcharge_gbp: 15.99, unit: 'per item' },
          { name: 'Peak Surcharge', surcharge_gbp: 0.50, unit: 'per item' },
        ],
      },
      volumetric_divisor_cc_per_kg: 4000,
    },
  },
  {
    // DHL Parcel UK — Zone D (Remote: Scotland Highlands, Islands, Crown Dependencies)
    courier_code: 'dhl',
    courier_name: 'DHL',
    service_code: 'dhl_parcel_zone_d',
    service_name: 'DHL Parcel UK — Zone D (Remote & Islands)',
    service_level: 'standard',
    shipment_mode: 'parcel',
    constraints: { required_packaging_type: 'parcel', max_weight_kg: 25 },
    metadata: {
      ready_for_api: false,
      category: 'parcel',
      integration_type: 'weight_size_tiers',
      zone: 'D',
      postcode_ranges: ['AB31–AB38', 'AB41–AB56', 'FK17–FK21', 'HS', 'IV', 'KA27–KA28', 'KW', 'PA20–PA50', 'PA60–PA78', 'PA80', 'PH14–PH44', 'PH49–PH50', 'ZE1–ZE3', 'Isle of Man (IM1–IM9)', 'Guernsey (GY1–GY10)', 'Jersey (JE1–JE5)'],
      tiers: [
        { name: 'Up to 25kg (NWD)', max_weight_kg: 25, service_level: 'next_working_day', cost_gbp: 12.75, per_kg_over: 0.75 },
        { name: 'Up to 25kg (2nd+)', max_weight_kg: 25, service_level: 'standard', cost_gbp: 10.75, per_kg_over: 0.75 },
      ],
      timed_services: [
        { name: 'Next Working Day By Noon', surcharge_gbp: 5.71 },
        { name: 'Next Working Day by 10:30am', surcharge_gbp: 6.89 },
        { name: 'Saturday', surcharge_gbp: 17.57 },
        { name: 'Saturday by 10:30am', surcharge_gbp: 12.19 },
      ],
      bagit_packs: [
        { size: 'Small', weight_range_kg: '1–2', cost_gbp: 4.90 },
        { size: 'Medium', weight_range_kg: '2+', cost_gbp: 4.90 },
        { size: 'Large', weight_range_kg: '5+', cost_gbp: 4.90 },
      ],
      surcharges: {
        heavy_weight_kg: [
          { min_kg: 5.01, max_kg: 10, surcharge_gbp: 1.50 },
          { min_kg: 10.01, max_kg: 20, surcharge_gbp: 15.00 },
          { min_kg: 20.01, max_kg: 30, surcharge_gbp: 25.00 },
          { min_kg: 30.01, max_kg: 32, surcharge_gbp: 30.00 },
          { min_kg: 34.01, max_kg: 36, surcharge_gbp: 40.00 },
          { min_kg: 36.01, max_kg: 500, surcharge_gbp: 50.00 },
        ],
        long_length_cm: [
          { min_cm: 100, max_cm: 119.99, surcharge_gbp: 1.00 },
          { min_cm: 120, max_cm: 139.99, surcharge_gbp: 5.00 },
          { min_cm: 140, max_cm: 159.99, surcharge_gbp: 6.00 },
          { min_cm: 160, max_cm: 179.99, surcharge_gbp: 9.00 },
          { min_cm: 180, max_cm: 199.99, surcharge_gbp: 14.00 },
          { min_cm: 200, max_cm: 219.99, surcharge_gbp: 21.00 },
          { min_cm: 220, max_cm: 239.99, surcharge_gbp: 26.00 },
          { min_cm: 240, max_cm: 259.99, surcharge_gbp: 31.00 },
          { min_cm: 260, max_cm: 279.99, surcharge_gbp: 39.00 },
          { min_cm: 280, max_cm: 299.99, surcharge_gbp: 51.00 },
          { min_cm: 300, max_cm: 319.99, surcharge_gbp: 56.00 },
          { min_cm: 320, max_cm: 339.99, surcharge_gbp: 65.00 },
          { min_cm: 340, max_cm: 10000, surcharge_gbp: 76.00 },
        ],
        other_services: [
          { name: 'Return to Sender', surcharge_gbp: 4.50, unit: 'per shipment' },
          { name: 'Compensation Charge', surcharge_gbp: 7.50, unit: 'per shipment' },
          { name: 'Carriage Charge', surcharge_gbp: 0.125, unit: 'per item' },
          { name: 'Booked in Delivery', surcharge_gbp: 15.99, unit: 'per item' },
          { name: 'Peak Surcharge', surcharge_gbp: 0.50, unit: 'per item' },
        ],
      },
      volumetric_divisor_cc_per_kg: 4000,
    },
  },
  {
    // Bisley's real current shipping operation for anything that doesn't fit a standard
    // carton (BOX-SMALL/MEDIUM/LARGE) — not a live-quoted courier, a flat cost per weight band
    // (confirmed with AIT). weight_tiers is editable via the shipping-services settings UI.
    courier_code: 'ait',
    courier_name: 'AIT',
    service_code: 'ait_freight',
    service_name: 'AIT Freight (Oversized / Non-Parcel)',
    service_level: 'standard',
    shipment_mode: 'freight',
    constraints: { required_packaging_type: 'freight' },
    metadata: {
      ready_for_api: false, category: 'freight', integration_type: 'weight_tiers',
      weight_tiers: [{ max_weight_kg: 29, cost_gbp: 40 }, { max_weight_kg: 68, cost_gbp: 52.5 }],
      percentage_of_price: 10, // legacy fallback, only used if weight_tiers is ever cleared
    },
  },
];

export const DEFAULT_PACKAGING_PROFILES: PackagingProfile[] = [
  {
    code: 'BOX-SMALL',
    name: 'Small Carton',
    package_type: 'parcel',
    inner_length_mm: 350,
    inner_width_mm: 250,
    inner_height_mm: 180,
    max_weight_grams: 10000,
    tare_weight_grams: 250,
    default_cost_gbp: 1.25,
  },
  {
    code: 'BOX-MEDIUM',
    name: 'Medium Carton',
    package_type: 'parcel',
    inner_length_mm: 500,
    inner_width_mm: 350,
    inner_height_mm: 250,
    max_weight_grams: 18000,
    tare_weight_grams: 450,
    default_cost_gbp: 2.1,
  },
  {
    code: 'BOX-LARGE',
    name: 'Large Carton',
    package_type: 'parcel',
    inner_length_mm: 700,
    inner_width_mm: 500,
    inner_height_mm: 400,
    max_weight_grams: 30000,
    tare_weight_grams: 900,
    default_cost_gbp: 3.8,
  },
  {
    // Anything too big for BOX-SMALL/MEDIUM/LARGE. Not a pallet or freight decision by itself —
    // the real courier (real UPS parcel quote, or AIT) is decided independently in
    // src/lib/shipping-decision.ts. Kept as a large catch-all bin footprint for packaging-profile
    // (physical box) selection purposes only.
    code: 'UPS-FREIGHT-CUSTOM-PALLET',
    name: 'Oversized / Non-Standard',
    package_type: 'freight',
    inner_length_mm: 3000,
    inner_width_mm: 2000,
    inner_height_mm: 2000,
    max_weight_grams: 500000,
    tare_weight_grams: 0,
    default_cost_gbp: null,
  },
];

export function isMissingRelationError(err: unknown): boolean {
  const e = err as { code?: string; message?: string };
  return e?.code === '42P01' || (e?.message ?? '').toLowerCase().includes('relation') && (e?.message ?? '').toLowerCase().includes('does not exist');
}
